import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ['Cormorant Garamond', 'Georgia', 'serif'],
        body: ['Montserrat', '-apple-system', 'sans-serif'],
        script: ['Great Vibes', 'cursive'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Premium color palette
        cream: "hsl(var(--cream))",
        ivory: "hsl(var(--ivory))",
        champagne: "hsl(var(--champagne))",
        sand: "hsl(var(--sand))",
        caramel: "hsl(var(--caramel))",
        espresso: "hsl(var(--espresso))",
        chocolate: "hsl(var(--chocolate))",
        gold: "hsl(var(--gold))",
        "gold-light": "hsl(var(--gold-light))",
        "gold-bright": "hsl(var(--gold-bright))",
        "gold-dark": "hsl(var(--gold-dark))",
        "gold-deep": "hsl(var(--gold-deep))",
        rose: "hsl(var(--rose))",
        blush: "hsl(var(--blush))",
        sage: "hsl(var(--sage))",
        terracotta: "hsl(var(--terracotta))",
        burgundy: "hsl(var(--burgundy))",
        "off-white": "hsl(var(--off-white))",
        brown: "hsl(var(--brown))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
        "3xl": "calc(var(--radius) + 16px)",
        "4xl": "2rem",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
        gold: "var(--shadow-gold)",
        "gold-lg": "var(--shadow-gold-lg)",
        "gold-xl": "var(--shadow-gold-xl)",
        inner: "var(--shadow-inner)",
        glow: "var(--shadow-glow)",
      },
      backgroundImage: {
        'gradient-gold': 'var(--gradient-gold)',
        'gradient-gold-shine': 'var(--gradient-gold-shine)',
        'gradient-gold-horizontal': 'var(--gradient-gold-horizontal)',
        'gradient-warm': 'var(--gradient-warm)',
        'gradient-hero': 'var(--gradient-hero)',
        'gradient-card': 'var(--gradient-card)',
        'gradient-premium': 'var(--gradient-premium)',
        'gradient-premium-dark': 'var(--gradient-premium-dark)',
        'gradient-rose': 'var(--gradient-rose)',
        'gradient-radial-gold': 'var(--gradient-radial-gold)',
        'gradient-radial-soft': 'var(--gradient-radial-soft)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
